### ISSUE TITLE
learning_lab_2.yml possible errors

### ISSUE THREAD

**Issue by nsherrar** [CiscoDevNet/sdwan-ansible-code#6]
Device_Template_Name is referenced in 3 tasks.
In "create_device_template", it is given value "**DeviceTemplate**", whereas in
"get_config_input" and "attach_device_template" it is given value "**DeviceTemplate1**"
Should all 3 be consistent?

Also, is it correct that "//system/host-name" is given a value of "**automatically**" as opposed to "**vedge03**" or similar?

**Comment by radtrentasei** [comment]
Thank you for pointing this out, I think now is fixed in the current main branch

Antonio
